### ISSUE TITLE
Wwidd needs "/media" directory

### ISSUE THREAD

**Issue by hlechner** [hlechner/wwidd#29]
If there is no directory: `/media` on system, the **wwidd** will throw error when try to add videos to library

**Comment by jeanlopes** [comment]
I will look whats happening =P

**Comment by hlechner** [comment]
For the workaround it's possible to create the directory (as root):

```
mkdir /media
```

File responsable for that:
`server/src/utils/system.js`:

``` javascript
...
        // default root paths
        if (empty) {
            paths = {
                'linux': ['home', 'media'],
                'cygwin': ['cygdrive'],
                'darwin': ['Users', 'Volumes']
            }[os] || ['home'];
        }
...
```
